# Generated by Django 5.1.3 on 2024-11-15 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('food_percent', models.PositiveIntegerField(default=60)),
                ('happiness_percent', models.PositiveIntegerField(default=60)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id', 'date_created'),
            },
        ),
    ]
