# Generated by Django 5.1.3 on 2024-11-16 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragons', '0003_alter_dragon_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 12, 34, 49, 156034, tzinfo=datetime.timezone.utc)),
        ),
    ]
