# Generated by Django 5.1.3 on 2024-11-16 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragons', '0004_alter_dragon_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
