# Generated by Django 5.1.3 on 2024-11-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_food_owned_user_treasure_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='food_owned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='treasure_owned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
